interface=uap0
driver=nl80211
ssid=Wifi Tree
hw_mode=g
channel=1
country_code=US
ieee80211d=1
wmm_enabled=1
auth_algs=1
macaddr_acl=0
ignore_broadcast_ssid=0
max_num_sta=25
# open network, no encryption
